name: CI

on:
  pull_request:
    branches:
      - develop
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 7
        run_install: false

    - name: Install Dependencies
      run: pnpm install

    - name: Run lint
      run: pnpm run lint
